### ISSUE TITLE
Add degruchy.org

### ISSUE THREAD

**Issue by ndegruchy** [kevquirk/512kb.club#10]
* **Domain name:** [degruchy.org][1]
* **GTMetrix results:** https://gtmetrix.com/reports/degruchy.org/V3gtfxDt/

Weight ~13kb. I actually added 1kb because I wanted it to *do something*, as opposed to some static page. Click on the first line to see.

[1]: https://degruchy.org/

**Comment by kevquirk** [comment]
Lol, that's really cool! Site has been added.
