### ISSUE TITLE
Two green sites

### ISSUE THREAD

**Issue by lucianmarin** [kevquirk/512kb.club#1032]
- https://lucianmarin.com/ — 40.9KB
- https://subreply.com/ — 47.8KB

Thank you!

**Comment by garritfra** [comment]
There's no way I can verify those page sizes. Please stick to the issue template. 🙂

**Comment by garritfra** [comment]
Did you mean to add these sites to the club? In that case, please open a pull request, as explained in our [FAQ](https://512kb.club/faq). 🙂
