### ISSUE TITLE
holehunter.com 105.9 KB

### ISSUE THREAD

**Issue by holehunter** [kevquirk/512kb.club#112]
holehunter.com
https://gtmetrix.com/reports/www.holehunter.com/vjgZbzGn/
105.9 KB

```
<li>
  <span class="before" style="--data-size:105.9;"></span>
  <span class="after">105.9 KB</span>
  <a class="site" target="blank" href="https://www.holehunter.com">holehunter.com</a>
</li>
```

**Comment by kevquirk** [comment]
Need GTMetrix link

**Comment by holehunter** [comment]
https://gtmetrix.com/reports/www.holehunter.com/vjgZbzGn/

**Comment by kevquirk** [comment]
Declined. Adult site.

**Comment by holehunter** [comment]
Thank you for your consideration. I understand. The submission information didn't have a prohibition against the category so I thought it was worth a shot as the site uses a lot of advanced optimization techniques to create a fully fledged experience under 67kb compressed on the initial visit and about 8kb compressed on subsequent visits. The user generated text is adult, but there there are no, and will never be any, pornographic pictures or video. The site also uses all responsible meta tags and warnings to identify its content to users.
