### ISSUE TITLE
I think that a1cy0n.xyz is breaking the rules

### ISSUE THREAD

**Issue by Xameren** [kevquirk/512kb.club#1155]
I'm not entirely sure, but it seems like this site, https://a1cy0n.xyz/, is a link page

**Comment by garritfra** [comment]
Yes, I agree. I'm out and about, do you have some spare time to remove that domain? Otherwise I'll do it in the coming days.

Thanks for reporting!🙂

**Comment by kevquirk** [comment]
I just did it. Thanks fore reporting, @Xameren
