### ISSUE TITLE
The GTmetrix on www.nytimes.com expired

### ISSUE THREAD

**Issue by Xameren** [kevquirk/512kb.club#1158]
Hello,
I noticed that the GTmetrix scan on www.nytimes.com, linked with the text "When popular website like [The New York Times](https://www.nytimes.com/) are [over 15MB in size](https://gtmetrix.com/reports/www.nytimes.com/Dz1IEZl0/)" has expired. 
I have therefore generated a new GTmetrix scan for the website that isn't expired: https://gtmetrix.com/reports/www.nytimes.com/8oflx2Mp/
I wish you a wonderful day to whoever is reading this,
-Xameren

**Comment by garritfra** [comment]
I don't think it's a good idea to renew this report, since it will expire again in 7 days. I'd rather remove it and update the claim. 🙂 Nice catch though.

**Comment by kevquirk** [comment]
Probably best to re-scan, download the PDF and link to the PDF I think.

**Comment by kevquirk** [comment]
Done :)
