### ISSUE TITLE
codevoid.de

### ISSUE THREAD

**Issue by c0dev0id** [kevquirk/512kb.club#123]
* **Domain name:**
https://codevoid.de

* **Link to GTMetrix results:**
https://gtmetrix.com/reports/codevoid.de/p182ySNc/

* **Uncompressed page size:**
7.69KB

Please fill in the following template too. It will speed up getting your site added. The example below uses `example.com` as the domain and an uncompressed page size of `81.4 KB`.

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:7.69;"></span>
  <span class="after">7.69 KB</span>
  <a class="site" target="blank" href="https://codevoid.de">codevoid.de</a>
</li>
```

**Comment by kevquirk** [comment]
Was actually 11.1KB - https://gtmetrix.com/reports/codevoid.de/xTUL2Pwc/

**Comment by c0dev0id** [comment]
Well, I'm adding and removing content. Fluctuation is to be expected.

Today its about 9k
https://gtmetrix.com/reports/codevoid.de/0QRN1vmc/

thanks
