### ISSUE TITLE
Improved performance of https://drgomesp.dev

### ISSUE THREAD

**Issue by drgomesp** [kevquirk/512kb.club#127]
I've made some improvements and tested again, with new results:

![image](https://user-images.githubusercontent.com/696982/103795767-26ce5300-5025-11eb-84b3-2b7e69786a01.png)

Could you please update it? :)

- Domain name: drgomesp.dev
- GTMetrix results: https://gtmetrix.com/reports/drgomesp.dev/x1rdEKlW/
- Uncompressed page size: 153.6 KB

**Comment by kevquirk** [comment]
I need you to complete the HTML template.

**Comment by drgomesp** [comment]
Thank you @kevquirk.
