### ISSUE TITLE
yne.fr

### ISSUE THREAD

**Issue by yne** [kevquirk/512kb.club#130]
* **Domain name:** https://yne.fr
* **Link to GTMetrix results:** https://gtmetrix.com/reports/yne.fr/Z4SJqAHm/
* **Uncompressed page size:** 17.5KB

```
<li>
  <span class="before" style="--data-size:17.5;"></span>
  <span class="after">17.5 KB</span>
  <a class="site" target="blank" href="https://yne.fr">yne.fr</a>
</li>
```

**Comment by kevquirk** [comment]
Not sure where 17.5 KB cam from. It's actually ~165.

**Comment by yne** [comment]
> Not sure where 17.5 KB cam from. It's actually ~165.

From the link above :

![image](https://user-images.githubusercontent.com/5113053/103863331-f3410680-50c0-11eb-95f5-d186d259c01f.png)

But chromium network inspector confirm that's it not the uncompressed value :
```
18.0 kB transferred 160 kB resources
```
I'll try to improve that ;)

**Comment by kevquirk** [comment]
Like it says on the site, I use the GT Metrix waterfall for all tests, so it's the same for everyone:

![](https://i.imgur.com/L76ycdO.png)
