### ISSUE TITLE
https://playerone.kevincox.ca/

### ISSUE THREAD

**Issue by kevincox** [kevquirk/512kb.club#132]
* **Domain name:** https://playerone.kevincox.ca/
* **Link to GTMetrix results:** https://gtmetrix.com/reports/playerone.kevincox.ca/kKJXFlqz/
* **Uncompressed page size:** 292.6KB

Please fill in the following template too. It will speed up getting your site added. The example below uses `example.com` as the domain and an uncompressed page size of `81.4 KB`.

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:292.6;"></span>
  <span class="after">292.6KB</span>
  <a class="site" target="blank" href="https://playerone.kevincox.ca">playerone.kevincox.ca</a>
</li>
```

**Comment by kevquirk** [comment]
Not sure what the point of this website is? It's ~300KB and doesn't appear to do anything but display the word "touch."?

**Comment by kevincox** [comment]
It is only useful on touchscreen devices.  It is a simple tool for picking a random person for things such as breaking into teams for games or deciding who goes first.
