### ISSUE TITLE
Navbar is looking Odd

### ISSUE THREAD

**Issue by Sumitwarrior7** [kevquirk/512kb.club#1322]
The navbar items are not aligned properly, they should be aligned symmetrically at center

**Comment by Sumitwarrior7** [comment]
![Screenshot from 2023-10-22 18-36-48](https://github.com/kevquirk/512kb.club/assets/108853577/2c0d9b8f-e59d-42bd-a110-ca218f24582e)

**Comment by Sumitwarrior7** [comment]
Buttons : Home, FAQ, RSS, Github are not looking good

**Comment by kevquirk** [comment]
That's how they're suppose to be.
