### ISSUE TITLE
Some porn /broken sites on your index

### ISSUE THREAD

**Issue by fschroiff** [kevquirk/512kb.club#1409]
https://lichess.org/

https://ebass.uk/

https://www.arizonabankruptcylawyer.org

https://holory.fr

http://freyx.co

Found by just randomly clicking around.

**Comment by veqqq** [comment]
What's was wrong with lichess? It's the most well known site on the list and looks fine atm.

**Comment by garritfra** [comment]
Thanks for reporting these sites. I removed them (except lichess, which does nothing wrong IMO) via [c4fcbd7](https://github.com/kevquirk/512kb.club/commit/c4fcbd7b88ef0cd88db1d6cb68d1a5815372f6f8).
