### ISSUE TITLE
broken/ad/malware sites

### ISSUE THREAD

**Issue by jonas-w** [kevquirk/512kb.club#1453]
Thanks for creating the 512k club! While browsing some of the pages I found these links that either were dead, redirected to ad/malware:

https://fz1.space/ does not exist anymore and redirects to a "this domain is for sale" page.

https://www.0chris.com/ redirects to stchris.net, but should be still eligible https://radar.cloudflare.com/scan/5154fccf-d9b1-4710-b4eb-f4e060cb9218/summary

https://saucecode.bar/ redirects to a page that uBlock Origin blocks as a malicious site.

https://closedgl2.github.io/ does not exist anymore, see this commit:
https://github.com/ClosedGL2/ClosedGL2.github.io/commit/82b4a7e93c99de9cf291f582c9607da7d0aa0ba4

https://notes.whoibrar.com/ redirects to link that uBlock origin blocks as a badware risk

https://luana.cc/ shows a cloudflare error page

~https://vern.cc seems to be dead, see https://codeberg.org/vern/website/issues/1~
Seems to be flaky, sometimes a 404, sometimes it can't connect, but sometimes it shows the correct page.

https://arc-x.org/ only shows 404

These do not open/resolve for me:

https://sm6kne.amprnet.se/

https://huma.id/

https://sverona.dev/

https://chibilinks.com/

https://hund.tty1.se/

https://stapy.magentix.fr/

https://eg-zine.cf/

**Comment by garritfra** [comment]
Thanks for reporting these sites! I'll have a look and remove them tomorrow. 🙂

**Comment by garritfra** [comment]
I assigned the good first issue tag since I currently lack the time to remove the entries. I eventually will, but if anyone wants to do it in the meantime, feel free!

**Comment by garritfra** [comment]
@jonas-w absolutely. That would help immensely! 🙂

**Comment by ttntm** [comment]
@jonas-w I had some time on my lunch break today and opened a PR - hope you don't mind :)

**Comment by garritfra** [comment]
Fixed by #1487
