### ISSUE TITLE
simbly.me (update)

### ISSUE THREAD

**Issue by thumbfighter** [kevquirk/512kb.club#149]
* **Domain name: simbly.me**
* **Link to GTMetrix results: https://gtmetrix.com/reports/simbly.me/QrcJmxsV/**
* **Uncompressed page size:1.9 KB**

Please fill in the following template too. It will speed up getting your site added. The example below uses `example.com` as the domain and an uncompressed page size of `81.4 KB`.

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:1.9;"></span>
  <span class="after">1.9 KB</span>
  <a class="site" target="blank" href="https://simbly.me">simbly.me</a>
</li>
```

**Comment by kevquirk** [comment]
In future, please let me know that this is an update to an existing submission.
