### ISSUE TITLE
Add stuts.uk

### ISSUE THREAD

**Issue by ColonelPanicks** [kevquirk/512kb.club#15]
* **Domain name:** stuts.uk
* **GTMetrix results:** https://gtmetrix.com/reports/stuts.uk/6spslfse/

**Comment by kevquirk** [comment]
Denied - 641KB uncompressed.

**Comment by ColonelPanicks** [comment]
Oops, sorry @kevquirk pasted the wrong report URL 🤦 

More recent one: https://gtmetrix.com/reports/stuts.uk/8ygVFMl5/ (212KB uncompressed)
