### ISSUE TITLE
bebyx.co.ua (update)

### ISSUE THREAD

**Issue by bebyx** [kevquirk/512kb.club#160]
* **Domain name:** bebyx.co.ua
* **Link to GTMetrix results:** https://gtmetrix.com/reports/bebyx.co.ua/yx87F9ME/
* **Uncompressed page size:** 6.9 KB

Fixed the favicon. :smiley: 

```
<li>
  <span class="before" style="--data-size:6.9;"></span>
  <span class="after">6.9 KB</span>
  <a class="site" target="blank" href="https://bebyx.co.ua">bebyx.co.ua</a>
</li>
```

**Comment by kevquirk** [comment]
Sorry, the site needs to be in English so I can check its contents.

**Comment by bebyx** [comment]
@kevquirk But you've already added my site https://fosstodon.org/@bebyx/105520938633837388. I just made it leaner.

**Comment by kevquirk** [comment]
I know I have other sites on there that aren't English. Problem is, I'm getting too many requests for non-English sites and I have no idea what they are.

I'll be working my way through the list and removing any non-English ones. I'm sure most are completely benign, but I've already had one site that turns out to be extremely political and I had no idea. I want no part of that. 

I'm sorry.

**Comment by bebyx** [comment]
I'm upset. 

However, it's your website, your rules. Just please make some disclaimer that 512club is for English-speaking masterrace only, not for Slavic scum.

Btw, machine translation could help in case you change your policy back to normal: https://rnpz5yal3lp2kcsly4y3zx7bwu-adwhj77lcyoafdy-bebyx-co-ua.translate.goog/

**Comment by kevquirk** [comment]
> English-speaking masterrace only, not for Slavic scum.

Ah, come on, let's try and keep this civil. This is nothing to do with race, but purely about my inability to ready any other language than English.

The machine translation is cool, I like that it's pretty transparent and easy to do. I'm gonna look for a browser plugin or something to see if I can make this easier. If I can find a way to quickly and easily translate sites, I'll go with that. This is already a lot of work to manage, so I want it to be simple.

**Comment by kevquirk** [comment]
I've found a plugin that will quickly translate the entire page, so I will use that from now on. Updated your page size too.

**Comment by bebyx** [comment]
@kevquirk 

Sorry for me being so impulsive. Sometimes I can't hide my frustration, when I see something, in my opinion, really unfair.

Great that you could work it out! I really appreciate your effort (and probably all other non-English-language minimalist website owners, too).
