### ISSUE TITLE
portable.fyi

### ISSUE THREAD

**Issue by cadars** [kevquirk/512kb.club#166]
* **Domain name:** portable.fyi
* **Link to GTMetrix results:** https://gtmetrix.com/reports/portable.fyi/jWk7vPSd/
* **Uncompressed page size:** 5.94 KB

```
<li>
  <span class="before" style="--data-size:5.94;"></span>
  <span class="after">5.94 KB</span>
  <a class="site" target="blank" href="https://portable.fyi">portable.fyi</a>
</li>
```

**Comment by kevquirk** [comment]
This site is 16.5 kb UNCOMPRESSED.
