### ISSUE TITLE
Settings CloudFlareURLScan

### ISSUE THREAD

**Issue by gablaxy** [kevquirk/512kb.club#1677]
Hello,
sorry if this was already answered in one of the issues.
As my title mentions, what setting do i select on CloudFlareURLScan ?
Because it doesn't accuratly scan my website...

**Comment by garritfra** [comment]
Hi, I'm not sure I understand the issue.

1. Go to https://radar.cloudflare.com/scan
2. Enter your site
3. Click on "Public" to run the scan
4. See "Bytes Total" metric

Maybe you've been using a different URL? Let me know if this works for you. 🙂

**Comment by gablaxy** [comment]
Hi,
I think I didn't explain it very well,
the scan isn't really counting the size of all the pages of my website, the Bytes Total is too low I think.

**Comment by kevquirk** [comment]
It's not supposed to count your entire website. It counts the page your submit, which for this, should be the homepage.

**Comment by gablaxy** [comment]
ok, but is the requirement only for the homepage to be under 512kb, because my website homepage is fit this but not some other pages of my website (I ask this question because for me, it isn't what the requirement is)

**Comment by kevquirk** [comment]
Just the homepage.

**Comment by gablaxy** [comment]
understood but isn't that a bit counterproductive ? Because my homepage fit your requirements but you clink on one link and you got a multiple mb page so I coule be featured on your list but my website isn't really <512kb

**Comment by gablaxy** [comment]
Fair enough, that wasn't what I understood after first reading the explanation on the website (I was thinking the requirement was the whole website under 512kb).
Thanks for your answer :)
