### ISSUE TITLE
Improved performance for drgomesp.dev

### ISSUE THREAD

**Issue by drgomesp** [kevquirk/512kb.club#168]
Hey @kevquirk 

Bigger performance improvement 😄 🎉 

![image](https://user-images.githubusercontent.com/696982/104313879-71355100-54b7-11eb-93fc-387076c0f8e2.png)

- Domain name: drgomesp.dev
- GTMetrix results: https://gtmetrix.com/reports/drgomesp.dev/bC0h9yi7/
- Uncompressed page size: 93 KB

Could you please update it? :)

**Comment by kevquirk** [comment]
Welcome to team green :-)

**Comment by drgomesp** [comment]
HAHA Thanks a lot! It has been quite a fun process!
