### ISSUE TITLE
airikr.me

### ISSUE THREAD

**Issue by e-edgren** [kevquirk/512kb.club#169]
* **Domain name:** https://airikr.me/?lang=en
* **Link to GTMetrix results:** https://gtmetrix.com/reports/airikr.me/iRVhOcxo/
* **Uncompressed page size:** 35.5 kB

```
<li>
  <span class="before" style="--data-size:35.5;"></span>
  <span class="after">35.5 KB</span>
  <a class="site" target="blank" href="https://airikr.me/?lang=en">airikr.me/?lang=en</a>
</li>
```

**Comment by e-edgren** [comment]
* **Domain name:** https://airikr.me/lang:en
* **Link to GTMetrix results:** https://gtmetrix.com/reports/airikr.me/VeOEQbAS/
* **Uncompressed page size:** 34.9 kB

```
<li>
  <span class="before" style="--data-size:34.9;"></span>
  <span class="after">34.9 KB</span>
  <a class="site" target="blank" href="https://airikr.me/lang:en">airikr.me/lang:en</a>
</li>
```

**Comment by e-edgren** [comment]
* **Domain name:** https://airikr.me/lang:en
* **Link to GTMetrix results:** https://gtmetrix.com/reports/airikr.me/qJufSYaa/
* **Uncompressed page size:** 17.7 kB

```
<li>
  <span class="before" style="--data-size:17.7;"></span>
  <span class="after">17.7 KB</span>
  <a class="site" target="blank" href="https://airikr.me/lang:en">airikr.me/lang:en</a>
</li>
```

**Comment by e-edgren** [comment]
* **Domain name:** https://airikr.me/lang:en
* **Link to GTMetrix results:** https://gtmetrix.com/reports/airikr.me/MmCpwsR8/
* **Uncompressed page size:** 14 kB

```
<li>
  <span class="before" style="--data-size:14;"></span>
  <span class="after">14 KB</span>
  <a class="site" target="blank" href="https://airikr.me/lang:en">airikr.me</a>
</li>
```

**Comment by kevquirk** [comment]
Please open a new issue so I can track is more easily.
