### ISSUE TITLE
ecliptik.com (update)

### ISSUE THREAD

**Issue by ecliptik** [kevquirk/512kb.club#194]
* **Domain name:** https://www.ecliptik.com
* **Link to GTMetrix results:** https://gtmetrix.com/reports/www.ecliptik.com/83P6RcY7/
* **Uncompressed page size:** 22.4 KB

(replaced Google Analytics with Goat Counter and removed jquery)

Please fill in the following template too. It will speed up getting your site added. The example below uses `example.com` as the domain and an uncompressed page size of `81.4 KB`.

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:22.4;"></span>
  <span class="after">22.4 KB</span>
  <a class="site" target="blank" href="https://www.ecliptik.com">ecliptik.com</a>
</li>
```

**Comment by kevquirk** [comment]
Great work. Welcome to the Green Team! :-)
