### ISSUE TITLE
JewishGen.org volunteer created and maintained web page

### ISSUE THREAD

**Issue by gregbmeyer** [kevquirk/512kb.club#195]
* Domain Name: kehilalinks.jewishgen.org
* **Link to GTMetrix results:  https://gtmetrix.com/reports/kehilalinks.jewishgen.org/JIDoDJ7X/:**
* **Uncompressed page size:  147kb:**
(new submission)
Please fill in the following template too.  It will...
<li>
  <span class="before" style="--data-size:147;"></span>
  <span class="after">147 KB</span>
  <a class="site" target="blank" href="https://kehilalinks.jewishgen.org/priluki/priluki.html">https://kehilalinks.jewishgen.org/priluki/priluki.html</a>
</li>
```

**Comment by kevquirk** [comment]
Please complete the template.

**Comment by gregbmeyer** [comment]
Updated the first part... the second is in html and displays as specified
What am I missing?

**Comment by kevquirk** [comment]
The HTML template appears when you create the issue. Need to complete that - instructions are included in the issue filler text.

**Comment by kevquirk** [comment]
Closing - lack of response.
