### ISSUE TITLE
http://topik.natenorthway.com

### ISSUE THREAD

**Issue by nnorthway** [kevquirk/512kb.club#196]
* **Domain name: http://topik.natenorthway.com**
* **Link to GTMetrix results: https://gtmetrix.com/reports/topik.natenorthway.com/NzfztKei/**
* **Uncompressed page size: 205.7kb**

Please fill in the following template too. It will speed up getting your site added. The example below uses `example.com` as the domain and an uncompressed page size of `81.4 KB`.

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:205.7;"></span>
  <span class="after">205.7 KB</span>
  <a class="site" target="blank" href="http://topik.natenorthway.com.com">http://topik.natenorthway.com</a>
</li>
```

**Comment by nnorthway** [comment]
@kevquirk looks like the link added has an extra ".com" at the end

**Comment by kevquirk** [comment]
Fixed
