### ISSUE TITLE
cri.dev

### ISSUE THREAD

**Issue by christian-fei** [kevquirk/512kb.club#198]
* **Domain name: https://cri.dev**
* **Link to GTMetrix results: https://gtmetrix.com/reports/cri.dev/LogLDFnk/**
* **Uncompressed page size: 84.7KB**

```
<li>
  <span class="before" style="--data-size:84.7;"></span>
  <span class="after">84.7 KB</span>
  <a class="site" target="blank" href="https://cri.dev">cri.dev</a>
</li>
```

**Comment by christian-fei** [comment]
Thanks!

**Comment by christian-fei** [comment]
Not sure if I should create a new issue, in case let me know @kevquirk 

---

* **Domain name: https://cri.dev**
* **Link to GTMetrix results: https://gtmetrix.com/reports/cri.dev/GYiAwYI0/**
* **Uncompressed page size: 55.2KB**

```
<li>
  <span class="before" style="--data-size:55.2;"></span>
  <span class="after">55.2 KB</span>
  <a class="site" target="blank" href="https://cri.dev">cri.dev</a>
</li>
```

**Comment by kevquirk** [comment]
New issue please.

**Comment by christian-fei** [comment]
done https://github.com/kevquirk/512kb.club/issues/244
