### ISSUE TITLE
Add josias.dev (36.7KB)

### ISSUE THREAD

**Issue by justjosias** [kevquirk/512kb.club#216]
* **Domain name:** [josias.dev](https://josias.dev)
* **Link to GTMetrix results:** https://gtmetrix.com/reports/josias.dev/Y32qLIe5/
* **Uncompressed page size:** 36.7KB

```
<li>
  <span class="before" style="--data-size:36.7;"></span>
  <span class="after">36.7 KB</span>
  <a class="site" target="blank" href="https://josias.dev">josias.dev</a>
</li>
```

**Comment by kevquirk** [comment]
GT Metrix reports 44.8 KB, so I've added it as that.
