### ISSUE TITLE
Request: Add jds.work to 512k club

### ISSUE THREAD

**Issue by juliusdelta** [kevquirk/512kb.club#220]
* **Domain name:**
https://jds.work
* **Link to GTMetrix results:**
https://gtmetrix.com/reports/jds.work/T3S2ZwiB/
* **Uncompressed page size:**
5.77KB

Please fill in the following template too. It will speed up getting your site added. The example below uses `example.com` as the domain and an uncompressed page size of `81.4 KB`.

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:5.77;"></span>
  <span class="after">5.77 KB</span>
  <a class="site" target="blank" href="https://jds.work">jds.work</a>
</li>
```

**Comment by kevquirk** [comment]
Site is actually 27.9 KB.
