### ISSUE TITLE
Request: add my homepage to the club

### ISSUE THREAD

**Issue by vvulpes0** [kevquirk/512kb.club#222]
* **Domain name: vvulpes0.github.io**
* **Link to GTMetrix results: https://gtmetrix.com/reports/vvulpes0.github.io/BxZ39sEW/**
* **Uncompressed page size: 164.8 KB**

Please fill in the following template too. It will speed up getting your site added. The example below uses `example.com` as the domain and an uncompressed page size of `81.4 KB`.

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:164.8;"></span>
  <span class="after">164.8 KB</span>
  <a class="site" target="blank" href="https://vvulpes0.github.io">vvulpes0.github.io</a>
</li>
```

**Comment by kevquirk** [comment]
FYI - looks like your favicon is broken.
