### ISSUE TITLE
blog.dgold.eu

### ISSUE THREAD

**Issue by dg01d** [kevquirk/512kb.club#227]
* **Domain name:**blog.dgold.eu
* **Link to GTMetrix results:**https://gtmetrix.com/reports/blog.dgold.eu/7EHWXnbZ/
* **Uncompressed page size:**78.5KB

Please fill in the following template too. It will speed up getting your site added. The example below uses `example.com` as the domain and an uncompressed page size of `81.4 KB`.

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:78.5;"></span>
  <span class="after">78.5 KB</span>
  <a class="site" target="blank" href="https://blog.dgold.eu">blog.dgold.eu</a>
</li>
```

**Comment by kevquirk** [comment]
FYI your favicon appears to be broken (see waterfall on GTMetrix)
