### ISSUE TITLE
thewismit.com

### ISSUE THREAD

**Issue by thewismit** [kevquirk/512kb.club#228]
* **Domain name:**
* thewismit.com
* **Link to GTMetrix results:**
* https://gtmetrix.com/reports/thewismit.com/xPO3VObe/
* **Uncompressed page size:**
* 16KB

Please fill in the following template too. It will speed up getting your site added. The example below uses `example.com` as the domain and an uncompressed page size of `81.4 KB`.

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:16;"></span>
  <span class="after">16 KB</span>
  <a class="site" target="blank" href="https://thewismit.com">thewismit.com</a>
</li>
```

**Comment by kevquirk** [comment]
FYI - looks like the link to your favicon is dead, looking at the waterfall on GTMetrix.

**Comment by thewismit** [comment]
Thanks Kev, appreciate it!
