### ISSUE TITLE
noblogo.org

### ISSUE THREAD

**Issue by filippodb** [kevquirk/512kb.club#229]
* **Domain name:**
* Noblogo.org
* **Link to GTMetrix results:**
* https://gtmetrix.com/reports/noblogo.org/UKtVBOLv/
* **Uncompressed page size:**
* 246KB

Please fill in the following template too. It will speed up getting your site added. The example below uses `example.com` as the domain and an uncompressed page size of `81.4 KB`.

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:246;"></span>
  <span class="after">246 KB</span>
  <a class="site" target="blank" href="https://noblogo.org">noblogo.org</a>
</li>
```

**Comment by kevquirk** [comment]
This site is actually 303.9 KB
