### ISSUE TITLE
caliandro.de

### ISSUE THREAD

**Issue by Caliandroid** [kevquirk/512kb.club#233]
* **Domain name:** Caliandro.de
* **Link to GTMetrix results:**  https://gtmetrix.com/reports/www.caliandro.de/YByPqtxn/
* **Uncompressed page size:** 130KB

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:130;"></span>
  <span class="after">130 KB</span>
  <a class="site" target="blank" href="https://www.caliandro.de">Caliandro.de</a>
</li>
```

**Comment by kevquirk** [comment]
Site was actually 134.9KB.

**Comment by Caliandroid** [comment]
> Site was actually 134.9KB.

Thank you @kevquirk .
I was following the metrics of GTMetrics and did not see the uncompressed value in the tab "waterfall".
