### ISSUE TITLE
airikr.me

### ISSUE THREAD

**Issue by e-edgren** [kevquirk/512kb.club#239]
* **Domain name:** https://airikr.me/lang:en
* **Link to GTMetrix results:** https://gtmetrix.com/reports/airikr.me/MmCpwsR8/
* **Uncompressed page size:** 14 kB

```
<li>
  <span class="before" style="--data-size:14;"></span>
  <span class="after">14 KB</span>
  <a class="site" target="blank" href="https://airikr.me/lang:en">airikr.me</a>
</li>
```

**Comment by kevquirk** [comment]
Website was down when I tested this.

**Comment by e-edgren** [comment]
Yeah. I've got a new speed from my broadband providor last night and my server got a new IP address because of this. I've updated the DNS so the website should work any minute now.
