### ISSUE TITLE
citizen428.net

### ISSUE THREAD

**Issue by citizen428** [kevquirk/512kb.club#250]
* **Domain name:** citizen428.net
* **Link to GTMetrix results:** https://gtmetrix.com/reports/citizen428.net/A7ZRMSGb/
* **Uncompressed page size:** 66kb

Please fill in the following template too. It will speed up getting your site added. The example below uses `example.com` as the domain and an uncompressed page size of `81.4 KB`.

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:66.0;"></span>
  <span class="after">66.0 KB</span>
  <a class="site" target="blank" href="https://citizen428.net">citizen428.net</a>
</li>
```

**Comment by kevquirk** [comment]
FYI your favicon appears to be dead in the waterfall.
