### ISSUE TITLE
dynamically generate markup for added sites

### ISSUE THREAD

**Issue by binyamin** [kevquirk/512kb.club#252]
Idea: use jekyll/eleventy/something-else to take in a json file and output the html. Instead of doing it by hand every single time.

**Comment by kevquirk** [comment]
Yeah, I've been thinking about doing this. The site is written by hand in HTML/CSS at the moment. I just need to set a couple of hours aside to migrate to Jekyll. At the moment it's a catch 22 where I have 10 mins here and there to add a few sites, but I don't have a couple hours to re-design it.

I really need to prioritise that though.

**Comment by binyamin** [comment]
I'd do it. I'm more comfortable with Eleventy, but I could do Jekyll if you want.

**Comment by kevquirk** [comment]
I really appreciate the offer, but it will be a fun weekend project. 😄

**Comment by kevquirk** [comment]
Had some time last night/today and managed to get this done. Also tweaked a couple other bits while I was at it.
