### ISSUE TITLE
512kB

### ISSUE THREAD

**Issue by przsak** [kevquirk/512kb.club#255]
Link to GTMetrix results: https://gtmetrix.com/reports/sakrajda.eu/aYz5en94/

Please fill in this simple template:

- domain: sakrajda.eu
  url: https://sakrajda.eu
  size: 465.5

Here's an example using `example.com` with a size of `21.4 KB`:

```
- domain: example.com
  url: https://example.com
  size: 21.4
```

**Comment by kevquirk** [comment]
Need link to GT Metrix.

**Comment by przsak** [comment]
Missed this bit, sorry: https://gtmetrix.com/reports/sakrajda.eu/aYz5en94/
