### ISSUE TITLE
ccw.icu

### ISSUE THREAD

**Issue by comcloudway** [kevquirk/512kb.club#268]
Please fill out **ALL ITEMS** below before submitting a new issue. If this is a for an update to an existing site, please ensure **"UPDATE"** is in the issue title.

Link to GTMetrix results: https://gtmetrix.com/reports/ccw.icu/scqX1LXT/
domain: ccw.icu
url: https://ccw.icu
size: 44.5 KB (53.7 KB Uncompressed)

EDIT: Updated size and link to GTMetrix results
EDIT2: Had to increase the size by 0.9kb after an update, updated the GTMetrix url to link to the results

**Comment by comcloudway** [comment]
Hi
I think that this issue was not resolved, as my domain wasn't added although it was stated in your commit message.
Regards Jakob #

**Comment by kevquirk** [comment]
Doh! Thanks for letting me know. I have no idea how I managed to do that. You're on there now though.

**Comment by comcloudway** [comment]
Suppose its because of my EDIT Fields, but thanks for fixing it so quick 👍
