### ISSUE TITLE
blog.khaleelgibran.com

### ISSUE THREAD

**Issue by khalby786** [kevquirk/512kb.club#271]
Please fill out **ALL ITEMS** below before submitting a new issue. If this is a for an update to an existing site, please ensure **"UPDATE"** is in the issue title.

Link to GTMetrix results: https://gtmetrix.com/reports/blog.khaleelgibran.com/3bsFHfXU/

```
- domain: blog.khaleelgibran.com
  url: https://blog.khaleelgibran.com/
  size: 476.3
```

**Comment by kevquirk** [comment]
How is this site 476KB??

**Comment by khalby786** [comment]
Is that too big or too small? 😄 

I used Vue. 😬

**Comment by kevquirk** [comment]
It's MASSIVE considering what the site contains.

**Comment by kevquirk** [comment]
It's vue. Over 50% of your site is JS. Anyway, you still qualified, but there are simple optimisations you can make to really slim it down.

**Comment by khalby786** [comment]
Noted, I'll slim it down!
