### ISSUE TITLE
0xff.nu

### ISSUE THREAD

**Issue by hxii** [kevquirk/512kb.club#274]
Link to GTMetrix results: https://gtmetrix.com/reports/0xff.nu/sigo7fWe/

```
- domain: 0xff.nu
  url: https://0xff.nu
  size: 5.92KB (12.9KB uncompressed)
```

**Comment by kevquirk** [comment]
Please complete the template properly.

**Comment by hxii** [comment]
> Please complete the template properly.

Apologies, updated.
