### ISSUE TITLE
UPDATE ethan.link

### ISSUE THREAD

**Issue by Booligoosh** [kevquirk/512kb.club#277]
Please fill out **ALL ITEMS** below before submitting a new issue. If this is a for an update to an existing site, please ensure **"UPDATE"** is in the issue title.

Link to GTMetrix results: https://gtmetrix.com/reports/ethan.link/K2XjYjye/#waterfall

```
- domain: ethan.link
  url: https://ethan.link/
  size: 88.7
```

**Comment by kevquirk** [comment]
🤣 love the scrolling marquee at the bottom of the page!

**Comment by Booligoosh** [comment]
Haha, thanks! 😁
