### ISSUE TITLE
lo.hn

### ISSUE THREAD

**Issue by Lohn** [kevquirk/512kb.club#280]
Link to GTMetrix results: 
https://gtmetrix.com/reports/lo.hn/BTFxJM8t/

```
- domain: lo.hn
  url: https://lo.hn
  size: 360KB
```

**Comment by kevquirk** [comment]
**UNCOMPRESSED** size of this site is ~800KB. Too big.

**Comment by Lohn** [comment]
Optimized the site:

https://gtmetrix.com/reports/lo.hn/RLchIhIl/
