### ISSUE TITLE
UPDATE mzumquadrat.de

### ISSUE THREAD

**Issue by ContainsLiquid** [kevquirk/512kb.club#289]
Please fill out **ALL ITEMS** below before submitting a new issue. If this is a for an update to an existing site, please ensure **"UPDATE"** is in the issue title.

**PLEASE PROVIDE THE UNCOMPRESSED SIZE ONLY**

Link to GTMetrix results: https://gtmetrix.com/reports/mzumquadrat.de/ANRttbzv/

```
- domain: mzumquadrat.de
  url: https://mzumquadrat.de
  size: 9.4
```

**Comment by kevquirk** [comment]
Just about to push your site to 512KB Club. I love what you've done with Simple.css, would you have any objections to me adding your site to the showcase please?

**Comment by ContainsLiquid** [comment]
> Just about to push your site to 512KB Club. I love what you've done with Simple.css, would you have any objections to me adding your site to the showcase please?

Sure, feel free to do so. :) Thank you for updating my site. :)

**Comment by kevquirk** [comment]
Thanks, just pushed it.
