### ISSUE TITLE
Request to add my website

### ISSUE THREAD

**Issue by Hund** [kevquirk/512kb.club#3]
I would like to add my website. It's 21.5 KB uncompressed. :)

* Homepage: https://hunden.linuxkompis.se
* Result: https://gtmetrix.com/reports/hunden.linuxkompis.se/yCUyOjsS/

**Comment by kevquirk** [comment]
Done

**Comment by Hund** [comment]
Thanks! :)

**Comment by Hund** [comment]
I have gotten it down to 13.5 KB now.
