### ISSUE TITLE
request for site to be added: https://fossphones.com

### ISSUE THREAD

**Issue by rav3ndust** [kevquirk/512kb.club#306]
Please fill out **ALL ITEMS** below before submitting a new issue. If this is a for an update to an existing site, please ensure **"UPDATE"** is in the issue title.

**PLEASE PROVIDE THE UNCOMPRESSED SIZE ONLY**

Link to GTMetrix results:https://gtmetrix.com/reports/fossphones.com/2WbNJ5iw/

```
- domain: fossphones.com
  url: https://fossphones.com
  size: 2.8 
```

Example completed template for `example.com` with an **UNCOMPRESSED** size of 72.5KB:

```
- domain: example.com
  url: https://example.com
  size: 72.5
```

**Comment by kevquirk** [comment]
You really should change the colours on your `nav` and `footer` they're unreadable.
