### ISSUE TITLE
justalecu.ro

### ISSUE THREAD

**Issue by AlecuMadalin32** [kevquirk/512kb.club#319]
Link to GTMetrix results: https://gtmetrix.com/reports/justalecu.ro/b3BSGz1A/

```
- domain: justalecu.ro
  url: https://justalecu.ro/
  size: 59.8KB
```

**Comment by kevquirk** [comment]
Site is ~280KB, not 59KB. Please replace the "green team" banner  with "blue team" banner on your footer.
