### ISSUE TITLE
UPDATE: Dante's blog

### ISSUE THREAD

**Issue by DanteAlighierin** [kevquirk/512kb.club#325]
https://gtmetrix.com/reports/dantealighierin.github.io/efNdYSFb/

```
- domain: dantealighierin.github.io
  url: https://dantealighierin.github.io
  size: 85.3
```

**Comment by kevquirk** [comment]
Lots of broken stuff in the waterfall and it's actually closer to 500KB. I'll let you figure all that out before I update.
