### ISSUE TITLE
UPDATE

### ISSUE THREAD

**Issue by tolstoevsky** [kevquirk/512kb.club#328]
Link to GTMetrix results: https://gtmetrix.com/reports/phreedom.club/j2qLa7Jh/

```
- domain: phreedom.club
  url: https://phreedom.club
  size: 229 
```

Example completed template for `example.com` with an **UNCOMPRESSED** size of 72.5KB:

```
- domain: example.com
  url: https://example.com
  size: 72.5
```

**Comment by kevquirk** [comment]
This site isn't already listed and it's nearly 500KB, not 229.
