### ISSUE TITLE
fanael.github.io, update

### ISSUE THREAD

**Issue by Fanael** [kevquirk/512kb.club#329]
Link to GTMetrix results: https://gtmetrix.com/reports/fanael.github.io/wFOdPlun/

```
- domain: fanael.github.io
  url: https://fanael.github.io/
  size: 28.3
```

**Comment by Fanael** [comment]
@kevquirk I'm afraid the site is listed twice now, with different sizes, the title *does* state this is an update.

**Comment by kevquirk** [comment]
Thanks, fixed it.
