### ISSUE TITLE
dejalavidavolar.org

### ISSUE THREAD

**Issue by dejalavidavolar** [kevquirk/512kb.club#330]
Please fill out **ALL ITEMS** below before submitting a new issue. If this is a for an update to an existing site, please ensure **"UPDATE"** is in the issue title.

**PLEASE PROVIDE THE UNCOMPRESSED SIZE ONLY**

Link to GTMetrix results: https://gtmetrix.com/reports/dejalavidavolar.org/ih624Qrs/

```
- domain: dejalavidavolar.org
  url: https://dejalavidavolar.org
  size: 27.0KB
```

Example completed template for `example.com` with an **UNCOMPRESSED** size of 72.5KB:

```
- domain: example.com
  url: https://example.com
  size: 72.5
```

**Comment by kevquirk** [comment]
**UNCOMPRESSED** the site is 124.5KB
