### ISSUE TITLE
ulpaulpa.de

### ISSUE THREAD

**Issue by ulpaulpa** [kevquirk/512kb.club#333]
Please fill out **ALL ITEMS** below before submitting a new issue. If this is a for an update to an existing site, please ensure **"UPDATE"** is in the issue title.

**PLEASE PROVIDE THE UNCOMPRESSED SIZE ONLY**

Link to GTMetrix results: https://gtmetrix.com/reports/ulpaulpa.de/MMhU2sTf/

```
- domain: ulpaulpa.de
  url: https://ulpaulpa.de
  size: 23.3
```

Example completed template for `example.com` with an **UNCOMPRESSED** size of 72.5KB:

```
- domain: example.com
  url: https://example.com
  size: 72.5
```

**Comment by kevquirk** [comment]
Please provide GTMetrix link...

**Comment by ulpaulpa** [comment]
Oh, didn't see that. I also updated the site size, it got 1.5 kb bigger, because I added the websitecarbon.com badge.
