### ISSUE TITLE
benj.lol

### ISSUE THREAD

**Issue by tzipor** [kevquirk/512kb.club#335]
Link to GTMetrix results: https://gtmetrix.com/reports/benj.lol/wcQzlJkU/

```
- domain: benj.lol
  url: https://benj.lol/
  size: 139 Bytes
```

**Comment by tzipor** [comment]
If you only want to include one domain per user, I would prefer that it be this one. I do intend to slightly increase the size of my other domain though, leaving room at the top for those who are competitive.

**Comment by kevquirk** [comment]
Not adding this one. It's not a site, just a couple of links.
