### ISSUE TITLE
bestmotherfucking.website

### ISSUE THREAD

**Issue by jtagcat** [kevquirk/512kb.club#35]
* **Domain name:** https://bestmotherfucking.website
* **GTMetrix results:** too lazy to get some other softw, probably checks out :)
* **Uncompressed page size:** 5.44kB

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:5.4;"></span>
  <span class="after">5.44 KB</span>
  <a class="site" href="https://bestmotherfucking.website">bestmotherfucking.website</a>
</li>
```

**Comment by kevquirk** [comment]
I think we're probably safe that this gem of a site is under 512KB, but I went ahead and checked anyway, 5.4KB confirmed. :-)

https://gtmetrix.com/reports/bestmotherfucking.website/hy2Y8rcd/

Added.
