### ISSUE TITLE
New site i21k.de

### ISSUE THREAD

**Issue by ashtonvandyke** [kevquirk/512kb.club#354]
Please fill out **ALL ITEMS** below before submitting a new issue. If this is a for an update to an existing site, please ensure **"UPDATE"** is in the issue title.

**PLEASE PROVIDE THE UNCOMPRESSED SIZE ONLY**

Link to GTMetrix results:
https://gtmetrix.com/reports/i21k.de/EHICa1S7/
```
- domain: i21k.de
  url: https://i21k.de/
  size: 2.5 kb
```

Example completed template for `example.com` with an **UNCOMPRESSED** size of 72.5KB:

```
- domain: example.com
  url: https://example.com
  size: 72.5
```

**Comment by kevquirk** [comment]
Your site is 2.5KB, then has an ~80KB favicon that is broken. I'd suggest fixing that and coming back as GTMetrix is reporting your site as 84KB.

**Comment by ashtonvandyke** [comment]
Uppps...
Changed!
https://gtmetrix.com/reports/i21k.de/cHoOXGDT/
