### ISSUE TITLE
wiki.4qq.org

### ISSUE THREAD

**Issue by JHenzi** [kevquirk/512kb.club#36]
* **Domain name:** wiki.4qq.org
* **GTMetrix results:** https://gtmetrix.com/reports/wiki.4qq.org/G7IrXwYZ/
* **Uncompressed page size:** 213KB

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:213KB;"></span>
  <span class="after">213KB</span>
  <a class="site" href="https://example.com">example.com</a>
</li>
```

**Comment by kevquirk** [comment]
Denied. Site is nearly 700KB **UNCOMPRESSED**

![](https://i.imgur.com/y1OtvXy.png)
