### ISSUE TITLE
Textpattern.com

### ISSUE THREAD

**Issue by philwareham** [kevquirk/512kb.club#365]
Please fill out **ALL ITEMS** below before submitting a new issue. If this is a for an update to an existing site, please ensure **"UPDATE"** is in the issue title.

**PLEASE PROVIDE THE UNCOMPRESSED SIZE ONLY**

Link to GTMetrix results: https://gtmetrix.com/reports/textpattern.com/VcVifDtI/

```
- domain:
  url: https://textpattern.com
  size: 463.3
```

Example completed template for `example.com` with an **UNCOMPRESSED** size of 72.5KB:

```
- domain: example.com
  url: https://example.com
  size: 72.5
```

**Comment by ndegruchy** [comment]
This site seems like it's at or over 600kb uncompressed.

![image](https://user-images.githubusercontent.com/52262673/118377867-e916a380-b59d-11eb-8507-648fd7fa18c4.png)

**Comment by kevquirk** [comment]
485.3kb according to GT Metrix.
