### ISSUE TITLE
thriftmac

### ISSUE THREAD

**Issue by newsonaut** [kevquirk/512kb.club#366]
Please fill out **ALL ITEMS** below before submitting a new issue. If this is a for an update to an existing site, please ensure **"UPDATE"** is in the issue title.

**PLEASE PROVIDE THE UNCOMPRESSED SIZE ONLY**

Link to GTMetrix results:

```
- domain:thriftmac.com
  url:https://thriftmac.com
  size:195.8
```

Example completed template for `example.com` with an **UNCOMPRESSED** size of 72.5KB:

```
- domain: example.com
  url: https://example.com
  size: 72.5
```

**Comment by kevquirk** [comment]
No GT Metrix link provided.

**Comment by kevquirk** [comment]
Now moved to a PR process. PLease see readme file for more info - https://github.com/kevquirk/512kb.club
