### ISSUE TITLE
LibreTranslate

### ISSUE THREAD

**Issue by argosopentech** [kevquirk/512kb.club#367]
Link to GTMetrix results: [GTMetrix LibreTranslate](https://gtmetrix.com/reports/libretranslate.com/OBGubZOM/)

```
- domain: libretranslate.com
  url: https://libretranslate.com
  size: 244.9
```

**Comment by PJ-Finlay** [comment]
Mirrors:
- https://translate.astian.org
- https://LibreTranslate.de

**Comment by ndegruchy** [comment]
This site loads over 600kb of uncompressed resources.

![image](https://user-images.githubusercontent.com/52262673/118377959-6a6e3600-b59e-11eb-8e89-af5d563531de.png)
