### ISSUE TITLE
Add saladhax.site

### ISSUE THREAD

**Issue by saladhax** [kevquirk/512kb.club#37]
* **Domain name: [saladhax.site](https://saladhax.site)**
* **GTMetrix results: https://gtmetrix.com/reports/saladhax.site/670Syfan/**
* **Uncompressed page size: 204.7kb**

Please fill in the following template too. It will speed up getting your site added. The example below uses `example.com` as the domain and an uncompressed page size of `81.4 KB`.

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:204.7;"></span>
  <span class="after">204.7 KB</span>
  <a class="site" href="https://example.com">saladhax.site</a>
</li>
```

**Comment by saladhax** [comment]
Updated GTMetrix Results: https://gtmetrix.com/reports/saladhax.site/ylFYTOSV/
Updated uncompressed size: 52.2kb

**Comment by kevquirk** [comment]
75% reduction. Good job!
