### ISSUE TITLE
conorr.glitch.me

### ISSUE THREAD

**Issue by littlegrapeguy** [kevquirk/512kb.club#370]
Please fill out **ALL ITEMS** below before submitting a new issue. If this is a for an update to an existing site, please ensure **"UPDATE"** is in the issue title.

**PLEASE PROVIDE THE UNCOMPRESSED SIZE ONLY**

Link to GTMetrix results:

https://gtmetrix.com/reports/conorr.glitch.me/7gajS81j/
- domain:glitch.me
  url:https://conorr.glitch.me
  size:79.3kb
```

Example completed template for `example.com` with an **UNCOMPRESSED** size of 72.5KB:

```
- domain: example.com
  url: https://example.com
  size: 72.5
```

**Comment by kevquirk** [comment]
Rejected. Please see [lightweight notice](https://512kb.club/#lightweight-notice)
