### ISSUE TITLE
Add last_checked to data files

### ISSUE THREAD

**Issue by kmutahar** [kevquirk/512kb.club#373]
I think that we should add a `last_check:` in the data files so that when sites are reviewed we can tell since it was last checked.

```
- domain: example.com
  url: http://example.com/
  size: 2.5
```

```
- domain: example.com
  url: http://example.com/
  size: 2.5
  last_checked: 20210517
```

This way from time to time when sites are check to make sure they can still be in the 512kb club and more specifically in the correct color team. 
Any site that was added before this being implemented can just have the `last_checked:` blank however, newer sites would have from when they are added.

`last_checked:` uses the following YYYYMMDD since it can make ordering them much easier.

**Comment by kevquirk** [comment]
While I agree that some kind of last check is helpful (I've already found a couple of dead links and removed them, never mind sites that no longer qualify) it's VERY difficult to maintain as the list grows.

I'm sure we can use something like GitHub actions to a) check the site is still up and b) check the size of the site.

Having said that, I have no idea how we could do that.

**Comment by kmutahar** [comment]
So my idea is a bit manual until we find an automated way to do it. For example one could from time to time search the data file using `last_checked: 202012` this would show everything that was checked in December 2020 and then we would manually check it in GTmetrix.

Or a command line that can provide the uncompressed size since GTmetrix has a limit on the number of checks at one time.

**Comment by kevquirk** [comment]
Based on the number of issues, we're in the region of ~350 sites on the 512KB Club. I'm concerned that this would be too much manual work. But yes, we do need a method of ensuring the maintaining members.

I think we need a check, but I don't think this is the right solution.

**Comment by lrmikestone** [comment]
It would be pretty trivial to rough up just a daily check without the "last checked" value just checking for whether the site is still up and running. I haven't looked and I don't know about a way to check the uncompressed size, but I'd imagine that this could be automated as well. Updating would still need to be a manual process as it would be much to easy to screw something up otherwise, but people handled updates on a daily basis (or even close to daily) it would keep things from getting out of hand.

**Comment by kmutahar** [comment]
@kevquirk there are 286 sites and 3 duplicate sites. I already started going over the blue team.

@lrmikestone the reason for me suggesting a "last checked" value is that so you would only need to search for the oldest records and check them every couple of days this way it won't get out of hand.

**Comment by kevquirk** [comment]
For the record, I've got no objection to adding a last checked date in the YAML - it won't be rendered on the front end, so whatever helps. :-)

Wow 3 duplicates - I'm clearly an idiot haha.
