### ISSUE TITLE
link to GitHub near the top

### ISSUE THREAD

**Issue by binyamin** [kevquirk/512kb.club#394]
Just to make life easier. Maybe with [tholman/github-corners](https://github.com/tholman/github-corners)?
###### Example of [tholman/github-corners](https://github.com/tholman/github-corners)
![image of 512kb.club with a github banner in the top corner](https://user-images.githubusercontent.com/39805353/120234999-1f535480-c227-11eb-8ada-96894ef905c3.png)

**Comment by kmutahar** [comment]
That is actually a really great idea. Maybe you can create the PR. If you need help with it let us know.

**Comment by binyamin** [comment]
Thanks! Are we going with the GitHub banner then? It doesn't look good below a width of 970 pixels. I feel like @kevquirk might want to weigh in here, since he's design-savvy.

**Comment by kmutahar** [comment]
@binyamin How are you thinking of the banner to look like. I just tried the corner and you are correct that it is a bit small.

**Comment by kevquirk** [comment]
I like the idea, I just think we need to consider how best to implement it so that it doesn't look "bolted on".

Maybe a revised layout slightly where the grey block at the top of the page incorporates it somehow. I'll have a think...

**Comment by kevquirk** [comment]
Had some time, so I added a banner below the main 512 title banner. Let me know what you guys think. I'm not married to it, so happy to make changes.

**Comment by kmutahar** [comment]
On mobile it looks great both dark and light mode.

**Comment by kmutahar** [comment]
@kevquirk when you created the banner you added an SVG logo to `assets/images/github-logo.svg` (not being reference anywhere) and also added an SVG to the defaults layout (Which is being used). 

was the github-logo.svg added my mistake or what happened.

**Comment by kevquirk** [comment]
Ah, good catch. I just removed it and pushed it. I originally went with adding an SVG, but ultimately decided to go with the SVG inline in HTML instead, so the colour could update between light and dark mode. Forgot to remove the SVG image. Sorted now.

**Comment by kmutahar** [comment]
Great I was making sure so that I can put the correct code in the includes folder to make it easier for others to read the defaults file
