### ISSUE TITLE
Update for editions-du-26-octobre

### ISSUE THREAD

**Issue by cara-tm** [kevquirk/512kb.club#410]
Hi.

We made a lot of optimization to reduce the website weight despite large amount of content and features.

We totalize now **182.7 Kb** (uncompressed) within the home page: https://gtmetrix.com/reports/editions-du-26-octobre.com/I9c2CID7/

Please, could you update our score? Thank you lot.

Best regards,
Patrick.

**Comment by kmutahar** [comment]
Hi can you please open a PR
