### ISSUE TITLE
invalid cert error on dejalavidavolar.org

### ISSUE THREAD

**Issue by Lex-2008** [kevquirk/512kb.club#448]
When working on the script to automatically update site sizes (like this PR: https://github.com/kevquirk/512kb.club/pull/445), I stumbled upon this.

Issue is that it causes the script to hang.

For now, I've work-arounded it by setting last_checked date for this site to 2021-04-11 (date of this issue: https://github.com/kevquirk/512kb.club/issues/338).

note to @dejalavidavolar: no urge to fix it right now from my side, but just to let you know.

**Comment by kmutahar** [comment]
@dejalavidavolar if around 2 weeks the issue is still not resolved the domain will be removed. 

You can readd it if removed by fixing the issue

**Comment by dejalavidavolar** [comment]
Sorry, my site is currently unavailable. Unfortunately I had some problems with the server where it was hosted. For now it is without certificate, so it would be better if you can remove it.

Thank you very much for contacting me and I hope you are well.

Regards
