### ISSUE TITLE
Sites for Review

### ISSUE THREAD

**Issue by kmutahar** [kevquirk/512kb.club#471]
### Light Weight

* https://cmdln.org/
* https://sugarfi.dev/
* https://sebastian.graphics/
* https://pablosgweb.com/
* https://proseandconst.xyz/
* https://anibalsolon.com/
* https://anibalsolon.com/
* https://blog.larsgerber.ch/
* https://xanny.family/

### Offline

Still need to be double-checked to insure its not ISP issues

* https://calibratemedia.ca/
* https://wor.do/

**Comment by kevquirk** [comment]
I've just pushed a couple of changes that likely remove most of these. Here's the commit messages:

```
Removed:   - ohio.araw.xyz (minimal)
Removed:   - rnbunker.neocities.org (minimal)   - jrballesteros05.codeberg.page (minimal)   - chtc.gitlab.io (minimal)
Removed   - justalecu.ro (unresponsive)   - maczan.pl (minimal)   - 1024b.club (minimal)   - tokiesan.github.io (minimal)   - salejandro.me (minimal)
```

**Comment by kevquirk** [comment]
My thoughts:

https://cmdln.org/ (not minimal - should stay)
https://sugarfi.dev/ (landing page - remove)
https://sebastian.graphics/ (not minimal - should stay)
https://pablosgweb.com/ (not minimal - should stay)
https://proseandconst.xyz/ (not minimal - should stay)
https://anibalsolon.com/ (not minimal - should stay)
https://blog.larsgerber.ch/ (minimal - remove)
https://xanny.family/ (minimal - remove)

**Comment by kmutahar** [comment]
## Orange Club

### Light Weight

* https://www.beh.uk/
* https://michel-slm.name/
* https://www.mutahar.me/
* https://tek256.com/
* https://gadonias.com/
* https://klokmork.com/
* https://ezra.website/
* https://codingbobby.xyz/
* https://mees.io/
* https://mvion.fr/
* https://drgomesp.dev/


### Offline

* https://cameron.otsuka.haus/
* https://www.stylix.ynh.fr/
* https://bnolet.me/

**Comment by kmutahar** [comment]
## Green Club

### Light Weight

* http://www.rullan.cat/
* https://binyam.in/
* https://zwieratko.sk/
* https://cosmo.red/
* https://radosavljevic.dev/
* https://astrophena.name/
* https://dev-nonsense.com/
* https://aboutdavid.me/
* https://idotmaster1.neocities.org/
* https://freshnode.net/


### Offline

* https://temp.sh/

**Comment by kevquirk** [comment]
http://www.rullan.cat/ - removed

    https://binyam.in/ - I feel that with an image, a menu, a nice design and an intro paragraph, this doesn't constitute "ultra light weight". Yes it's light weight, but not ultra, I don't think.

    https://zwieratko.sk/ - removed

    https://cosmo.red/ - removed

    https://radosavljevic.dev/ - removed

    https://astrophena.name/ - removed

    https://dev-nonsense.com/ - removed

    https://aboutdavid.me/ - removed

    https://idotmaster1.neocities.org/ - removed

    https://freshnode.net/ - this isn't ultra minimal.

Offline

    https://temp.sh/ - site is now online.

**Comment by morfismo** [comment]
https://anibalsolon.com/  just a links page

**Comment by kevquirk** [comment]
> https://anibalsolon.com/ just a links page
> 
> https://obelous.com/ just a links page
> 
Both of these sites have a proper design to them though - they both qualify.

> https://pablosgweb.com/ just a links page
This site is down, I've removed it.
