### ISSUE TITLE
Do we need to move to another SSG?

### ISSUE THREAD

**Issue by kevquirk** [kevquirk/512kb.club#494]
@kmutahar I read this today. Do we need to consider a move to something like Hugo or 11ty?

https://www.bridgetownrb.com/future/rip-jekyll/

**Comment by kmutahar** [comment]
For the short term, I don't think we need to switch to another SSG but maybe in the long term if we don't see any updates from Jekyll we can start thinking about that. 

I tried searching to see if there are other sources about this and the only thing I found was a post by the author of the article on Jekyll Talk Discourse

https://talk.jekyllrb.com/t/the-future-of-jekyll/6414

**Comment by kevquirk** [comment]
Yeah, I don't think we should rush into changing platform, but worth being cognisant of, just so we're prepared (if needed).
