### ISSUE TITLE
xpil.eu

### ISSUE THREAD

**Issue by xpil** [kevquirk/512kb.club#50]
* **Domain name:**
https://xpil.eu

* **GTMetrix results:**
https://gtmetrix.com/reports/xpil.eu/Wfi1V2yD/

* **Uncompressed page size:**
413.7 kB

Please fill in the following template too. It will speed up getting your site added. The example below uses `example.com` as the domain and an uncompressed page size of `81.4 KB`.

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:413.7;"></span>
  <span class="after">413.7 KB</span>
  <a class="site" target="blank" href="https://xpil.eu/">xpil.eu</a>
</li>
```

**Comment by xpil** [comment]
I managed to optimize my blog even further. It is now 221KB. It was fun!

https://gtmetrix.com/reports/xpil.eu/EG4Nt2Y1/

**Comment by kevquirk** [comment]
50% reduction - good job! Welcome to team orange! :-)
