### ISSUE TITLE
Random site button?

### ISSUE THREAD

**Issue by kevquirk** [kevquirk/512kb.club#509]
Just had an idea, what about adding a button to the top of the page so that people can visit a random site from the club?

Haven't looked into how to do it, but I'm pretty sure it would be simple.

Thoughts?

**Comment by kmutahar** [comment]
Something like what "Weird Wide Webring" does?

It would be a cool feature, and would increase activity on people's sites. 

I'll also start looking at away. I believe it would require some Javascript

**Comment by kevquirk** [comment]
Exactly like WW Web Ring. 😊

That project is open source, so I'm sure we can probably repurpose the randomisation code - I'm sure Jack won't mind.

I've no objections to introducing a little JS as long as it respects the visitors.
