### ISSUE TITLE
probably wrong way of measuring 

### ISSUE THREAD

**Issue by vhodus** [kevquirk/512kb.club#540]
I was interested in the site https://ebass.uk/, it contains many images. If you check using https://gtmetrix.com/, then it really is less than 512 kb.
But if you download the site to your hard drive, then it weighs 7 mb, of which 4.7 mb are images of guitars.
Therefore, I did not understand the criterion on the basis of which you include sites in the 512 Club. Do you measure the maximum weight of each page / or only main page? Or the whole site?

**Comment by kevquirk** [comment]
We measure the size of the site that is transmitted to a visitor, which is what GT Metrix measures. There is no right or wrong way of measuring the page weight, this is just the standardised way we chose.
