### ISSUE TITLE
jeremysarber.com

### ISSUE THREAD

**Issue by jeremysarber** [kevquirk/512kb.club#60]
* **Domain name:** https://jeremysarber.com
* **GTMetrix results:** 
* **Uncompressed page size:** 124.8 KB

Please fill in the following template too. It will speed up getting your site added. The example below uses `example.com` as the domain and an uncompressed page size of `81.4 KB`.

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:81.4;"></span>
  <span class="after">81.4 KB</span>
  <a class="site" target="blank" href="https://example.com">example.com</a>
</li>
```

**Comment by kevquirk** [comment]
Please complete the template and provide the GTMetrix link.

**Comment by jeremysarber** [comment]
https://gtmetrix.com/reports/jeremysarber.com/aNANyeDQ/

**Comment by kevquirk** [comment]
Please complete the template per the original issue notes.

**Comment by jeremysarber** [comment]
* **Domain name:** https://jeremysarber.com
* **GTMetrix results:** https://gtmetrix.com/reports/jeremysarber.com/aNANyeDQ/
* **Uncompressed page size:** 124.8 KB

Please fill in the following template too. It will speed up getting your site added. The example below uses `example.com` as the domain and an uncompressed page size of `81.4 KB`.

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:81.4;"></span>
  <span class="after">81.4 KB</span>
  <a class="site" target="blank" href="https://example.com">example.com</a>
</li>
```

**Comment by kevquirk** [comment]
To be clear, I was talking about filling in the HTML template like this:

```
   <li>
      <span class="before-orange" style="--data-size:125.1;"></span>
      <span class="after">125.1 KB</span>
      <a class="site" target="blank" href="https://jeremysarber.com/">jeremysarber.com</a>
  </li>
```
I've done it for you and added the site to the list.
