### ISSUE TITLE
Sites with Error to contact owners

### ISSUE THREAD

**Issue by kmutahar** [kevquirk/512kb.club#605]
```
- domain: matt-smiley.com
  url: https://matt-smiley.com/
  size: 358
  last_checked: 2021-10-21
```
@mgsesq Since you added this domain #519 Please fix the SSL Error. You can then notify me to be added again or create a new PR.

```
- domain: noJS.club
  url: https://noJS.club/
  size: 26.7
  last_checked: 2021-10-01
```
@karan Since you added this domain #97 Please fix the SSL Error. You can then notify me to be added again or create a new PR.

```
- domain: pablosgweb.com
  url: https://pablosgweb.com/
  size: 371
  last_checked: 2021-09-19
```
@PSGrobet Since you added this domain #212 The domain name has expired. If renewed you can then notify me to be added again or create a new PR.

**Comment by weex** [comment]
These were all merged or closed so this can probably be closed.

**Comment by kmutahar** [comment]
@weex Thanks
