### ISSUE TITLE
Definition of "site"

### ISSUE THREAD

**Issue by prijks** [kevquirk/512kb.club#624]
Sorry if I'm being dense or overthinking things, but I'd like to better understand how "site" is defined and I couldn't find anything in the FAQ or previous issues.

The home page of my website weighs in at 40.9 KB uncompressed. This is the size GTMetrix would report if I submitted it. But my site consists of many more pages than just my home page. Pages without images mostly range in the 50-100 KB range and pages with images usually come in at 200-500 KB. A handful of pages are larger where it makes sense for them to be. The aggregate size of all content on my site is easily in the hundreds of MB, though. Yet I wouldn't call it bloated, since most users are only going to consume a few hundred KB of it. So I'm trying to figure out where I fit in.

The 512kb.club website uses both the term site and page but doesn't define how it uses either. Could you clarify? Does my site qualify? And if so, which team do I qualify for? I have browsed other sites in the club to try to get a feel for this, and I think I could submit my site mostly guilt-free, but I'd like to make sure I'm sticking to the spirit of the rules and not just the letter.

I think what is holding me up most is the phrase "total UNCOMPRESSED web resources" under the requirements. Since as I said, across my entire site, the total is in the hundreds of MB...

I think this question applies beyond just me (but maybe not since it hasn't been asked yet) but in case it helps, my site is at https://www.esgeroth.org/

**Comment by kmutahar** [comment]
This would be better answered by @kevquirk 

If no comment is left within a week I can try to answer this.

**Comment by kevquirk** [comment]
We measure your homepage. If it qualifies and isn't "ultra minimal" it's fine.
