### ISSUE TITLE
Unable to measure XHTML site?

### ISSUE THREAD

**Issue by m7a** [kevquirk/512kb.club#630]
Hello,

I just found this lovely project and wanted to try measuring my site. When I enter my URL `https://masysma.lima-city.de/`, I receive the following error: ”Analysis Error / Lighthouse Error: The URL did not appear to be an HTML page”. I guess the message is probably right because my page is served as `application/xhtml+xml`.

Not sure if my page would qualify -- it depends on the resolution of #624. The “home” page has only about ~20 KiB whereas some subpages have large images and thus even in the order of ~20 MiB! I can tell that the entire website including all subpages (even non-linked ones) and resources is 60 MiB. From a quick glance it could be that 12 of 194 subpages are above the 512 KiB limit :)

**Comment by kevquirk** [comment]
You would need to be able to measure the page to be added. Happy for you to use a different tool if GT Metrix doesn't work.
