### ISSUE TITLE
michel-slm.name

### ISSUE THREAD

**Issue by michel-slm** [kevquirk/512kb.club#66]
* **Domain name:** https://michel-slm.name/
* **GTMetrix results:** https://gtmetrix.com/reports/michel-slm.name/OQMIxAPQ/
* **Uncompressed page size:** 241.8 KB

```
<li>
  <span class="before" style="--data-size:241.8;"></span>
  <span class="after">241.8 KB</span>
  <a class="site" target="blank" href="https://michel-slm.name/">michel-slm.name</a>
</li>
```

**Comment by kevquirk** [comment]
Great work with the optimisation - enjoyed reading your post about it.
