### ISSUE TITLE
Lęgua

### ISSUE THREAD

**Issue by vladas-palubinskas** [kevquirk/512kb.club#79]
* **Domain name:** az.on.lt
* **GTMetrix results:** A https://gtmetrix.com/reports/az.on.lt/9xtcGMJA/
* **Uncompressed page size:** 24.5 KB

Please fill in the following template too. It will speed up getting your site added. The example below uses `example.com` as the domain and an uncompressed page size of `81.4 KB`.

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:24.5;"></span>
  <span class="after">24.5 KB</span>
  <a class="site" target="blank" href="https://az.on.lt">az.on.lt</a>
</li>
```

**Comment by kevquirk** [comment]
Please add a gtmetrix link

**Comment by vladas-palubinskas** [comment]
Wops! B today, instead of A yesterday for the same… Probably for not using CDN?

**Comment by vladas-palubinskas** [comment]
Linked to GTMetrix.
