### ISSUE TITLE
Wrong measurement?

### ISSUE THREAD

**Issue by danger89** [kevquirk/512kb.club#807]
I was measuring my site (melroy.org) to looking for improvements (guhguh.. fontawesome). And I also checked our website. 

Result of your website: https://gtmetrix.com/reports/512kb.club/kv8iYe0p/

On your `GET /` page it reports a size of 9.22KB.  
But with all the resources (css, js, images,..) says 105Kb uncompressed.

I think your site should now be placed in The Orange Team, right?

Do I look at the wrong measurements? Or is your website not reflecting the current state, I'm confused now.

Regards,
Melroy

**Comment by kmutahar** [comment]
You are correct our site is 105kb but we have it listed as 91.50kb, which will move it to orange. This is due to not updating the site sizes list. We will try to do it more frequently but life sometimes gets in the way.

**Comment by kmutahar** [comment]
If you would like to help with the site check you can see the automation file that checks the size and updates the code base.

Let me know if interested so I can explain it more in detail.

**Comment by danger89** [comment]
> If you would like to help with the site check you can see the automation file that checks the size and updates the code base.
> 
> Let me know if interested so I can explain it more in detail.

I'm interested. You could use github actions. Or gitlab runners to automate this in regular intervals.

**Comment by danger89** [comment]
I think somebody already is doing this GH Action idea: https://github.com/kevquirk/512kb.club/pull/749
