### ISSUE TITLE
no-JS.club

### ISSUE THREAD

**Issue by fr-an-kh** [kevquirk/512kb.club#810]
Since the **noJS.club** is no longer active because the **Git repo has been archived**, I figured it's time to bring this wonderful project back to life!

So here comes the successor **[The no-JS Club](https://no-js.club)**

<hr>

Link to GTMetrix results: https://gtmetrix.com/reports/no-js.club/rRl4R3Jm/

section: no-js.club
url: https://no-js.club/
size: 25.6 kb

**Comment by kmutahar** [comment]
Thank you for the entry however we no longer use issues to add a domain to the list, please open a PR
