### ISSUE TITLE
vladas.palubinskas.lt

### ISSUE THREAD

**Issue by vladas-palubinskas** [kevquirk/512kb.club#82]
* **Domain name:** vladas.palubinskas.lt
* **GTMetrix results:** A https://gtmetrix.com/reports/vladas.palubinskas.lt/KQ4NtNAe/
* **Uncompressed page size:** 9.7 KB

Please fill in the following template too. It will speed up getting your site added. The example below uses `example.com` as the domain and an uncompressed page size of `81.4 KB`.

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:9.7;"></span>
  <span class="after">9.7 KB</span>
  <a class="site" target="blank" href="https://vladas.palubinskas.lt">vladas.palubinskas.lt</a>
</li>
```

**Comment by kevquirk** [comment]
Please add a link to GTMetrix, per the instructions.

**Comment by vladas-palubinskas** [comment]
Where, as GTMetrix results? Done.
