### ISSUE TITLE
Add 512kb.club website to the about section

### ISSUE THREAD

**Issue by danger89** [kevquirk/512kb.club#820]
You know that you can add a website to the about section in GitHub?

I would fill-in :https://512kb.club in your case.

Go to the repository details on GitHub by click on this gear icon:

![image](https://user-images.githubusercontent.com/628926/166604921-0c0767dd-024a-43a0-bb58-37a48a3d027f.png)

Hint: Also consider adding GitHub Topics, so your project will be better found within GitHub and search engines in general.

Regards,
Melroy vd Berg

**Comment by kmutahar** [comment]
@kevquirk This is a great idea if you can do it since I don't have the proper access.

**Comment by danger89** [comment]
@kevquirk?

**Comment by kevquirk** [comment]
Done :-)
