### ISSUE TITLE
Add test.jameskupke.com

### ISSUE THREAD

**Issue by jameskupke** [kevquirk/512kb.club#84]
* **Domain name:** test.jameskupke.com
* **GTMetrix results:** https://gtmetrix.com/reports/test.jameskupke.com/OtQd14pz/
* **Uncompressed page size:** 7.70KB

Please fill in the following template too. It will speed up getting your site added. The example below uses `example.com` as the domain and an uncompressed page size of `81.4 KB`.

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:7.7;"></span>
  <span class="after">7.7 KB</span>
  <a class="site" target="blank" href="https://test.jameskupke.com">test.jameskupke.com</a>
</li>
```

**Comment by kevquirk** [comment]
512 KB Club is for **live** sites, not **test** sites.

**Comment by jameskupke** [comment]
Howdy Kev. That's the URL for my live site. I admit that it may be a bit confusing. I will consider renaming and reaching out again.
