### ISSUE TITLE
myipaddress.ru

### ISSUE THREAD

**Issue by vickodin** [kevquirk/512kb.club#89]
* **Domain name:** myipaddress.ru
* **GTMetrix results:** https://gtmetrix.com/reports/myipaddress.ru/vxhaZHCS/
* **Uncompressed page size:** 1.1 KB
```
<li>
  <span class="before" style="--data-size:1.1;"></span>
  <span class="after">1.1 KB</span>
  <a class="site" target="blank" href="https://myipaddress.ru">myipaddress.ru</a>
</li>
```

**Comment by kevquirk** [comment]
Need GTMetrix results

**Comment by vickodin** [comment]
> Need GTMetrix results

Done :)
Thanks in advance!
