### ISSUE TITLE
Post screenshot of the site as a PR comment

### ISSUE THREAD

**Issue by garritfra** [kevquirk/512kb.club#954]
This would help spot UM sites more quickly and potentially speed up the review flow.

I haven't thought about how this could be implemented, but I'm sure there is a way.
I'm open for suggestions!

**Comment by kevquirk** [comment]
I suppose the obvious answer would be to have the submitter post a screenshot in the short-term. I'm sure there's probably a way to automate this though.

I think it's a great idea.

**Comment by garritfra** [comment]
There seems to be an action for this:

https://github.com/marketplace/actions/comment-webpage-screenshot

I'll take a look at it after work. :)

**Comment by garritfra** [comment]
Closing this, as I think the value we gain from this is close to none. We have to open the GTMetrix link anyway, which shows a screenshot of the site.
