### ISSUE TITLE
Allow actions to run for first time contributors

### ISSUE THREAD

**Issue by garritfra** [kevquirk/512kb.club#955]
Currently we have to manually allow running actions from new contributors and wait for it to finish, which is a bit time consuming.

I propose to allow workflow runs for first time contributors whenever a PR is opened, as per [this](https://github.com/garritfra/garrit.xyz/settings/actions) setting:

![grafik](https://user-images.githubusercontent.com/32395585/189864279-286e7f9d-2ab7-4ee2-928f-d1272115f5cd.png)

**Comment by kevquirk** [comment]
Done :)
