### ISSUE TITLE
https://nojs.club/

### ISSUE THREAD

**Issue by karan** [kevquirk/512kb.club#97]
* **Domain name:** https://nojs.club/
* **GTMetrix results:** https://gtmetrix.com/reports/nojs.club/cKfBHSdF/
* **Uncompressed page size:** 4.26KB

Please fill in the following template too. It will speed up getting your site added. The example below uses `example.com` as the domain and an uncompressed page size of `81.4 KB`.

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:4.26;"></span>
  <span class="after">4.26 KB</span>
  <a class="site" target="blank" href="https://noJS.club">noJS.club</a>
</li>
```

**Comment by kevquirk** [comment]
Was 24.6, not 4.26.
